apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
  namespace: analytics
data:
  superset_config.py: |
    from superset.config import *

    
    SQLALCHEMY_DATABASE_URI = 'clickhouse://default:@clickhouse:9000/default'
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    
    SECRET_KEY = os.getenv('SUPERSET_SECRET_KEY', 'your_default_secret_key')

   
    SUPERSET_WEBSERVER_PORT = 8088
